### PR TITLE
Fix snap count release

### LINKED ISSUE #17: Missing 2018 passing data in nflreadr:load_pfr_advstats
Hi, 
I want to use PFR's advanced passing stats from seasons 2018 to 2021, but the loaded dataset consists rows only 2019 to 2021. Reinstalling the package did not fix the issue. 

Here is the code I'm using to load PFR data. 
`load_pfr_advstats(seasons = 2018:2021, stat_type = 'pass', summary_level = 'season'). `

### LINKED ISSUE #20: DEN @ SEA missing in Load_Snap_Counts
1. **Have you installed the latest development version of the package(s) in question? **

Yes

2. **Describe the bug**

When loading Load_Snap_Counts, Denver and Seattle's snaps are still missing. When summarizing the data, only 30 teams show up available for the week.

3. **Reprex**

```r

snaps <- nflreadr::load_snap_counts(2022:2022)%>%
  group_by(team)%>%
  summarize(players=n())

```

4. **Expected Behaviour**

When running the function, I assumed Denver and Seattle's snaps from MNF would be available by now. But as of this morning, they are not pulling in.

5. **nflverse_sitrep()**

<details>
  <summary> sitrep </summary>
  
  ```r
-- System Info --------------------------------------------------------------------------------------------------------------------------------
* R version 4.1.2 (2021-11-01)   * Running under: Windows 10 x64 (build 22000)
-- nflverse Packages --------------------------------------------------------------------------------------------------------------------------
* nflreadr (1.3.0)  * nflseedR (1.1.0)  * nflplotR (1.1.0)  
* nflfastR (4.4.0)  * nfl4th   (1.0.2)  * nflverse (1.0.2)  
-- nflverse Options ---------------------------------------------------------------------------------------------------------------------------
No options set for nflreadr, nflfastR, nflseedR, nfl4th, nflplotR, and nflverse
-- nflverse Dependencies ----------------------------------------------------------------------------------------------------------------------
* askpass     (1.1)     * gtable      (0.3.1)    * progressr    (0.11.0)   
* bit         (4.0.4)   * hms         (1.1.2)    * proto        (1.0.0)    
* bit64       (4.0.5)   * httr        (1.4.4)    * purrr        (0.3.4)    
* cachem      (1.0.6)   * isoband     (0.2.5)    * R6           (2.5.1)    
* cli         (3.3.0)   * janitor     (2.1.0)    * rappdirs     (0.3.3)    
* clipr       (0.8.0)   * jsonlite    (1.8.0)    * RColorBrewer (1.1-3)    
* codetools   (0.2-18)  * labeling    (0.4.2)    * Rcpp         (1.0.9)    
* colorspace  (2.0-3)   * lattice     (0.20-45)  * readr        (2.1.2)    
* cpp11       (0.4.2)   * lifecycle   (1.0.1)    * rlang        (1.0.5)    
* crayon      (1.5.1)   * listenv     (0.8.0)    * rstudioapi   (0.14)     
* curl        (4.3.2)   * lubridate   (1.8.0)    * scales       (1.2.1)    
* data.table  (1.14.2)  * magick      (2.7.3)    * snakecase    (0.11.0)   
* digest      (0.6.29)  * magrittr    (2.0.3)    * stringi      (1.7.8)    
* dplyr       (1.0.10)  * MASS        (7.3-54)   * stringr      (1.4.1)    
* ellipsis    (0.3.2)   * Matrix      (1.3-4)    * sys          (3.4)      
* fansi       (1.0.3)   * memoise     (2.0.1)    * tibble       (3.1.8)    
* farver      (2.1.1)   * mgcv        (1.8-38)   * tidyr        (1.2.0)    
* fastmap     (1.1.0)   * mime        (0.12)     * tidyselect   (1.1.2)    
* fastrmodels (1.0.2)   * munsell     (0.5.0)    * tzdb         (0.3.0)    
* furrr       (0.3.1)   * nlme        (3.1-153)  * utf8         (1.2.2)    
* future      (1.28.0)  * openssl     (2.0.2)    * vctrs        (0.4.1)    
* generics    (0.1.3)   * parallelly  (1.32.1)   * viridisLite  (0.4.1)    
* ggplot2     (3.3.6)   * pillar      (1.8.1)    * vroom        (1.5.7)    
* globals     (0.16.1)  * pkgconfig   (2.0.3)    * withr        (2.5.0)    
* glue        (1.6.2)   * prettyunits (1.1.1)    * xgboost      (1.6.0.1)  
* gsubfn      (0.7)     * progress    (1.2.2)     

  ```
</details>

6. **Screenshots**

7. **Additional context**

Thanks for all that you guys do. I appreciate it.

### PR DESCRIPTION
**Pull request by mrcaseb**
The update script had an issue with release new snap count data to nflverse-data because of some GitHub latency. New data are released from local runner now. 

Also some minor code formatting and improvements

### CODE REVIEW

File: auto/update_snap_counts.R [hunk 1]
```diff
@@ -2,9 +2,11 @@ pkgload::load_all()
 
 scrape_snaps <- function(){
 
-  completed_games <- piggyback::pb_download_url(file = "scraped_games.csv",
-                                                repo = "nflverse/nflverse-pfr",
-                                                tag = "snap_counts_raw") |>
+  completed_games <- piggyback::pb_download_url(
```
Comment (tanho63) [inline auto/update_snap_counts.R]: csv_from_url would be fine, I was lazy at the time

Comment (mrcaseb) [reply auto/update_snap_counts.R]: done

**Comment by mrcaseb** [comment]
Updated adv. passing stats parser to be able to scrape 2018, fixing #17

**Review by tanho63 — APPROVED** [review]
